[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
build_flags =
  -DENABLE_DEBUG
lib_deps =
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer
  bblanchon/ArduinoJson
  https://github.com/gicking/LIN_master_portable_Arduino.git
  robtillaart/X9C10X
